# site settings

title:          Mary Samanta
tagline:        Software Engineer
url:            https://mairyss.github.io/
baseurl:        /
permalink:      pretty
repo:           https://github.com/MairySs/MairySs.github.io

# author settings

author:
  name:         Mary Samanta
  email:        samantam1717@gmail.com
photo:          /assets/photo2.jpg

# build settings

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .git
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

sass:
  sass_dir:     _sass
  sourcemap:    never

feed:
  path:         atom.xml

autopages:
  enabled:      false

pagination:
  enabled:      true
  per_page:     1
  sort_reverse: true
  permalink:    /:num/
  title:        ":title &middot; Page :num"
